php:
  build: images/centos
  volumes:
    - "/home/cristian/Docker/dockerphp533/Code/reporttv-ws:/var/www/html"
    - "/home/cristian/Docker/dockerphp533/bin/composer.phar:/usr/local/bin/composer"
    - "/home/cristian/Docker/dockerphp533/conf/php.ini:/etc/php.ini"
  working_dir: /var/www/html
  ports:
    - "80:80"
